Setup omeda+identityX & add new newsletter signup/login components
parameter1/ab-media-websites pull request #186
Opened 2022-06-17 13:39 UTC by B77Mills

REQUIRES: https://github.com/parameter1/base-cms/pull/352 & https://github.com/parameter1/identity-x/pull/16
 - Add Env variable to enable newsletter functionality
 - Add simple configurations for the newsletter signup pushdown and inline boxes
 - Create new pushdown & inline components that use the login component.  
 -- New component send login link and forces user to reVerify their account(forcing /user/profile to display)
 - Move Premium Parters block to above container to prevent it from pushing down with the newsletter pushdown

@todo: Figure out best way to track these events within GTM/UA.

### Pushdown:
<img width="1120" alt="Screen Shot 2022-06-22 at 10 32 32 AM" src="https://user-images.githubusercontent.com/3845869/175083304-322b650f-179c-4276-85a5-1411c7894265.png">
<img width="1147" alt="Screen Shot 2022-06-22 at 10 32 44 AM" src="https://user-images.githubusercontent.com/3845869/175083334-7906e34a-608f-4737-80f5-3b08e8249776.png">

### Inline:
<img width="1111" alt="Screen Shot 2022-06-22 at 10 38 36 AM" src="https://user-images.githubusercontent.com/3845869/175083575-90e0715d-979d-40bc-9062-7be24bb79637.png">
<img width="1106" alt="Screen Shot 2022-06-22 at 10 38 47 AM" src="https://user-images.githubusercontent.com/3845869/175083605-7b5678ac-9da8-4b3a-8563-2491db618ef0.png">

Authenticate & Profile ### Pages(Step2):
<img width="789" alt="Screen Shot 2022-06-22 at 11 22 14 AM" src="https://user-images.githubusercontent.com/3845869/175084294-d6b98488-ccc4-49d5-bf29-7129135ad648.png">

2022-06-17 13:49 UTC, B77Mills commented
![](https://github.trello.services/images/mini-trello-icon.png) [AB: Newsletter Signup Info](https://trello.com/c/fFXh9l6Y/294-ab-newsletter-signup-info)

2022-06-17 14:30 UTC, solocommand requested changes

2022-06-17 14:30 UTC, solocommand commented on packages/global/config/identity-x.js
> +    'regionCode',
`regionCode` and `postalCode` should _not_ be required server-side -- these values cannot be specified for non-US/CA users and will result in a permanent gate.

2022-06-17 14:30 UTC, solocommand commented on packages/global/config/identity-x.js
> +  ],
You have an extra array nested here

2022-06-17 14:30 UTC, solocommand commented on packages/global/start-server.js
> +      console.log('omeda config: ', omedaConfig);
Remove log

2022-06-17 14:30 UTC, solocommand commented on sites/aquamagazine.com/config/newsletter.js
> +    imagePath: 'files/base/p1/sandbox/image/static/newsletter-phone-full.png',
Does this exist? I'm not seeing it...

2022-06-17 14:30 UTC, solocommand commented on sites/woodfloorbusiness.com/package.json
> +    "newrelic": "^6.4.1"
Why is newrelic being included in the site? It should be used in the shared start-server utility

2022-06-17 16:33 UTC, B77Mills commented on sites/aquamagazine.com/config/newsletter.js
> +    imagePath: 'files/base/p1/sandbox/image/static/newsletter-phone-full.png',
These are loaded in S3 under the normal bucket, but in the p1/sandbox path instead of a specific org/tenant:
**https://img.woodfloorbusiness.com/files/base/p1/sandbox/image/static/newsletter-phone-half.png?auto=format%2Ccompress&w=280&dpr=2**
<img src="https://img.woodfloorbusiness.com/files/base/p1/sandbox/image/static/newsletter-phone-half.png?auto=format%2Ccompress&w=280&dpr=2" />
**https://img.woodfloorbusiness.com/files/base/p1/sandbox/image/static/newsletter-phone-full.png?auto=format%2Ccompress&w=280&dpr=2**
<img src="https://img.woodfloorbusiness.com/files/base/p1/sandbox/image/static/newsletter-phone-full.png?auto=format%2Ccompress&w=280&dpr=2" />

2022-06-17 16:34 UTC, B77Mills commented on sites/woodfloorbusiness.com/package.json
> +    "newrelic": "^6.4.1"
@solocommand I messed that up.  I had the wrong package.json open and didnt catch it.  This has been fixed.

2022-06-17 16:49 UTC, solocommand approved these changes

2022-06-29 14:23 UTC, solocommand requested changes

2022-06-29 14:23 UTC, solocommand commented on packages/global/components/layouts/content/default.marko
> +          <identity-x-newsletter-form-inline config-name="signupBannerLarge" />
`config-name` won't do anything with this component

2022-06-29 14:23 UTC, solocommand commented on packages/global/components/site-footer.marko
> +          <else-if(!newsletterConfig.disabled && newsletterConfig.action)>
What is `staticNewsletterConfig` -- I don't see it in this PR. `signupBannerStatic` maybe? I'd recommend just moving this logic into a new component within monorail and using it here and on RR. Call it `theme-newsletter-form-external` or something

2022-06-29 19:27 UTC, B77Mills commented on packages/global/components/site-footer.marko
> +          <else-if(!newsletterConfig.disabled && newsletterConfig.action)>
@solocommand  Deps have been upgraded and it will now use the new newsletter-banner-external component with the config-name passed in for content and feed blocks.  The footer just used the default from monorail.

2022-06-29 20:47 UTC, solocommand requested changes

2022-06-29 20:47 UTC, solocommand commented on packages/global/config/identity-x.js
> +    'postalCode',
Don't require `postalCode` in server-side validation fields, this will prevent gating from working for anyone with a non-US/CA address.

It can remain in the client-side fields, as the client form knows to skip that field when a different country is selected.

2022-06-29 20:47 UTC, solocommand commented on packages/global/start-server.js
>        // Use billboardState middleware
Replace the i18n (L56-58) and newsletterState (L64) with the middlewares from the monorail package. No need to have local copies of them

2022-06-29 20:47 UTC, solocommand commented on yarn.lock
> +"@parameter1/base-cms-marko-web-theme-monorail@^2.101.0":
Re-run yarn/dep upgrades, looks like it added a new version of monorail instead of updating the existing one.

2022-07-05 15:03 UTC, merged